version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-southeast-2:274201610284:task-definition/pensioner-details-service:1"
        LoadBalancerInfo:
          ContainerName: "pensioner-details-service"
          ContainerPort: "8082"
# Optional properties
        PlatformVersion: "LATEST"
